### ISSUE TITLE
Functors blog post

### ISSUE THREAD

**Issue by kyldvs** [andywhite37/blog#12]
Cool blog post! Was reading through it had a question and noticed a bug in example code:

1. I believe you need `...`  before the map call: `| [head, ...tail] => [f(head), ...map(f, tail)]` on [L393](https://github.com/andywhite37/blog/blame/master/content/posts/2019-11-01-a-laymans-guide-to-functors-in-reasonml.md#L393)
2. Should the [first functor law](https://github.com/andywhite37/blog/blame/master/content/posts/2019-11-01-a-laymans-guide-to-functors-in-reasonml.md#L224) more accurately be: `map(id, fa) == fa;` (not `===`)? `==` is structural equality, and your `List` functor fails the law as written: [sketch](https://sketch.sh/s/VDWSVmDtCAqUehGR64sYU0/)

**Comment by andywhite37** [comment]
Ah, yes indeed, I need the `...` - thanks.  For some of the example code, I was kind of spitballing it without testing... shame on me.

For the `===` that was kind of pseudocode to indicate that the things should be equal, but I agree that it's confusing to be in the code like that.

**Comment by kyldvs** [comment]
Yeah I figured it was something like that :) not a big deal either way! Since there was no explanation of difference between `===` and `==` figured it wouldn't really affect the blog content when using the more correct one.

Feel free to close this with/without fixing these !

Cool blog post, looking forward to the others you mentioned on Relude's issue!

**Comment by andywhite37** [comment]
No, thank you!  I appreciate the feedback and you taking the time to read it and try the examples.  I hope to integrate the examples with sketch.sh or some other playground site in the near future, but haven't quite gotten there yet.

I think the list example is fixed, and I tried to clarify the use of `==` for both functor laws.

Thanks again - feel free to re-open or open other issues if you find anything else!
