### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ruifortes** [andywhite37/blog#14]
I guess you meant "function" here:
https://github.com/andywhite37/blog/blame/master/content/posts/2019-11-01-a-laymans-guide-to-functors-in-reasonml.md#L231

**Comment by andywhite37** [comment]
Hmm - I think I actually meant to say `functor` there, but it's possible that's the wrong terminology. I was trying to impart the idea that if you have a functor `f a`, and you map the identity function `a -> a` over it, you just get back your original functor `f a` unchanged.

The term "functor" being an overloaded concept in ReasonML/OCaml makes this more confusing too.

**Comment by ruifortes** [comment]
ah...ok, don't get my word for it, I'm just starting :-)

**Comment by andywhite37** [comment]
No worries, thanks for posting!
